- hosts: node1
  max_fail_percentage: 30
  serial: 30%
  vars:
    app_name: flask-demo
    app_version: v2
  tasks:
  - name: stop app
    docker_container:
      name: "{{ app_name }}"
      state: stopped
  - name: run app
    shell: "docker run --network=host -d {{ tagName }}"
  - name: wait for app port start
    wait_for: port=5000
  - name: Check app health
    uri:
      method: GET
      url: "http://{{ ansible_host }}:5000/healthz"



